# -*- coding: utf-8 -*-
"""DATA CLEANING AND PREPARATION

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OVqMkSdxhIofvjZ2AJ7I-Es2cDh1LCUg
"""

import pandas as pd
df = pd.read_csv("/content/sample_data/Sample - Superstore.csv", encoding='latin1')
print(df.head())
print("\nMissing Values:")
print(df.isnull().sum())
print("\nDuplicate Rows:")
print(df.duplicated().sum())
df = df.drop_duplicates()
df['Order Date'] = pd.to_datetime(df['Order Date'], errors='coerce')
df['Ship Date'] = pd.to_datetime(df['Ship Date'], errors='coerce')
print("\nData Types:")
print(df.dtypes)
df.to_csv("/content/sample_data/Cleaned_Superstore.csv", index=False)
print("\nCleaned dataset saved successfully!")